"""
Convert trained weights from JSON to Coq syntax.

Usage:
    python src/export_coq.py weights.json > weights.v
    python src/export_coq.py weights.json --output coq/Weights.v
"""

import argparse
import json
import sys


def weight_to_coq(w):
    """Convert a single weight to Coq Z syntax."""
    w = int(w)
    if w >= 0:
        return str(w)
    else:
        return f"({w})"


def weights_list_to_coq(weights):
    """Convert a list of weights to Coq list syntax."""
    return "[" + "; ".join(weight_to_coq(w) for w in weights) + "]"


def layer_to_coq(name, weights, biases):
    """Convert a layer (weights matrix + biases) to Coq definition."""
    lines = [f"Definition {name} : list (list weight * bias) :="]

    neurons = []
    for i, (ws, b) in enumerate(zip(weights, biases)):
        ws_coq = weights_list_to_coq(ws)
        b_coq = weight_to_coq(b)
        neurons.append(f"    ({ws_coq}, {b_coq})")

    lines.append("  [" + ";\n   ".join(neurons) + "].")
    return "\n".join(lines)


def output_layer_to_coq(name, weights, biases):
    """Convert output layer (single neuron) to Coq definition."""
    ws = weights[0]
    b = biases[0]
    ws_coq = weights_list_to_coq(ws)
    b_coq = weight_to_coq(b)
    return f"Definition {name} : list weight * bias :=\n  ({ws_coq}, {b_coq})."


def json_to_coq(data):
    """Convert full JSON weights to Coq definitions."""
    output = []

    output.append("(** Trained weights - auto-generated by export_coq.py *)")
    output.append("")

    if "layer1" in data:
        l1 = data["layer1"]
        output.append(layer_to_coq("layer1_weights", l1["weight"], l1["bias"]))
        output.append("")

    if "layer2" in data:
        l2 = data["layer2"]
        output.append(layer_to_coq("layer2_weights", l2["weight"], l2["bias"]))
        output.append("")

    if "output" in data:
        out = data["output"]
        output.append(output_layer_to_coq("output_weights", out["weight"], out["bias"]))
        output.append("")

    output.append("(** Verify with: vm_compute. reflexivity. *)")
    output.append("Lemma weights_valid :")
    output.append("  check_all_8bit layer1_weights layer2_weights output_weights = true.")
    output.append("Proof. vm_compute. reflexivity. Qed.")
    output.append("")
    output.append("Theorem network_verified :")
    output.append("  forall xs, In xs (all_inputs 8) -> network xs = parity xs.")
    output.append("Proof.")
    output.append("  apply network8_correct.")
    output.append("  exact weights_valid.")
    output.append("Qed.")

    return "\n".join(output)


def main():
    parser = argparse.ArgumentParser(description="Convert JSON weights to Coq syntax")
    parser.add_argument("input", help="Input JSON file")
    parser.add_argument("--output", "-o", help="Output file (default: stdout)")
    args = parser.parse_args()

    with open(args.input, "r") as f:
        data = json.load(f)

    coq_code = json_to_coq(data)

    if args.output:
        with open(args.output, "w") as f:
            f.write(coq_code)
            f.write("\n")
        print(f"Wrote Coq definitions to {args.output}", file=sys.stderr)
    else:
        print(coq_code)


if __name__ == "__main__":
    main()
